import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_deck/flutter_deck.dart';

import '../dependency_graph/graph_model.dart';
import '../dependency_graph/graph_view.dart';
import '../theme.dart';
import '../widgets/design.dart';

/// Interactive dependency graph of a real app.
///
/// Data: assets/dependency_graph.json, generated by
/// `dart run tool/export_dependency_graph.dart <snapshot.json>` from a
/// dependency_inspector snapshot.
class DependencyGraphSlide extends FlutterDeckSlideWidget {
  const DependencyGraphSlide()
    : super(
        configuration: const FlutterDeckSlideConfiguration(
          route: '/dependency-graph',
          title: '04. Dependency graph',
          steps: 2,
          speakerNotes:
              '- This is the real dependency graph of my app, not an illustration.\n'
              '- Step 1 is what I wrote in pubspec.yaml; step 2 is everything my build pulls in. '
              'The number counts up as the transitive dependencies appear.\n'
              '- Click a package: gold = what it depends on, white = who depends on it.\n'
              '- Drag to pan, scroll / pinch to zoom, double-click to reset.\n'
              '- Dependencies are not bad: they are why we can build this efficiently and ship this fast.',
        ),
      );

  @override
  Widget build(BuildContext context) {
    return FlutterDeckSlide.blank(
      builder: (context) => const DesignSlide(
        padded: false,
        pageNumber: '04',
        child: _GraphBody(),
      ),
    );
  }
}

class _GraphBody extends StatefulWidget {
  const _GraphBody();

  @override
  State<_GraphBody> createState() => _GraphBodyState();
}

class _GraphBodyState extends State<_GraphBody> {
  static GraphData? _cache;

  late final Future<GraphData> _graph = _cache != null
      ? Future.value(_cache)
      : rootBundle
            .loadString('assets/dependency_graph.json')
            .then(
              (s) => _cache = GraphData.fromJson(
                jsonDecode(s) as Map<String, dynamic>,
              ),
            );

  final _viewKey = GlobalKey<DependencyGraphViewState>();
  int? _sel;

  @override
  Widget build(BuildContext context) {
    return FutureBuilder<GraphData>(
      future: _graph,
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Center(
            child: Text(
              'Failed to load graph: ${snapshot.error}',
              style: fig(28),
            ),
          );
        }
        final graph = snapshot.data;
        if (graph == null) return const SizedBox.shrink();
        final all = {for (var i = 0; i < graph.nodes.length; i++) i};

        return FlutterDeckSlideStepsBuilder(
          builder: (context, step) {
            final showAll = step >= 2;
            final visible = showAll ? all : graph.directSet;
            final count =
                (showAll ? graph.nodes.length : graph.directSet.length) - 1;
            return Stack(
              children: [
                Positioned(
                  left: 100,
                  right: 100,
                  top: 200,
                  bottom: 110,
                  child: DependencyGraphView(
                    key: _viewKey,
                    graph: graph,
                    visible: visible,
                    onSelectionChanged: (i) => setState(() => _sel = i),
                  ),
                ),
                Positioned(
                  left: 120,
                  top: 84,
                  child: IgnorePointer(
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.baseline,
                      textBaseline: TextBaseline.alphabetic,
                      children: [
                        CountUp(
                          count,
                          style: fig(98, color: DeckColors.accent, height: 1),
                        ),
                        const SizedBox(width: 28),
                        Text(
                          showAll
                              ? 'dependencies, direct and transitive'
                              : 'direct dependencies',
                          style: fig(32, color: DeckColors.faint),
                        ),
                      ],
                    ),
                  ),
                ),
                Positioned(
                  left: 120,
                  bottom: 100,
                  child: IgnorePointer(child: _Legend(graph: graph)),
                ),
                if (_sel != null)
                  Positioned(
                    right: 120,
                    top: 96,
                    child: _SelectionInfo(
                      graph: graph,
                      index: _sel!,
                      visible: visible,
                    ),
                  ),
              ],
            );
          },
        );
      },
    );
  }
}

class _Legend extends StatelessWidget {
  const _Legend({required this.graph});

  final GraphData graph;

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        for (final eco in Ecosystem.values)
          if (graph.countOf(eco) > 0)
            Padding(
              padding: const EdgeInsets.only(right: 40),
              child: Row(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Container(
                    width: 14,
                    height: 14,
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: ecoColor(eco),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Text.rich(
                    TextSpan(
                      style: fig(26, color: DeckColors.faint),
                      children: [
                        TextSpan(text: '${ecoLabel(eco)} '),
                        TextSpan(
                          text: '${graph.countOf(eco)}',
                          style: fig(26, color: DeckColors.accent),
                        ),
                      ],
                    ),
                  ),
                ],
              ),
            ),
        Text(
          'Filled = direct   ·   Outline = transitive',
          style: fig(24, color: DeckColors.faintest),
        ),
      ],
    );
  }
}

class _SelectionInfo extends StatelessWidget {
  const _SelectionInfo({
    required this.graph,
    required this.index,
    required this.visible,
  });

  final GraphData graph;
  final int index;
  final Set<int> visible;

  @override
  Widget build(BuildContext context) {
    final node = graph.nodes[index];
    final down = graph.closure(index, out: true, visible: visible).length - 1;
    final up = graph.closure(index, out: false, visible: visible).length - 1;
    return IgnorePointer(
      child: Container(
        padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 18),
        decoration: BoxDecoration(
          color: DeckColors.background.withValues(alpha: 0.88),
          border: Border.all(color: DeckColors.rule),
          borderRadius: BorderRadius.circular(4),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisSize: MainAxisSize.min,
          children: [
            Text(
              node.version.isEmpty
                  ? node.name
                  : '${node.name}  ${node.version}',
              style: mono(24, color: DeckColors.text),
            ),
            const SizedBox(height: 10),
            Text('depends on $down', style: fig(24, color: DeckColors.accent)),
            Text('used by $up', style: fig(24, color: DeckColors.sub)),
          ],
        ),
      ),
    );
  }
}
